docker-registry:
  image: registry:2
  ports:
    - "5000:5000"
  labels:
    io.rancher.sidekicks: docker-storage,docker-cache
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: docker=registry
  links:
    - docker-cache
    - docker-storage
  volumes_from:
    - docker-storage
    - docker-cache
  environment:
    SETTINGS_FLAVOR: local
    STORAGE_PATH: /var/lib/docker/registry
    SEARCH_BACKEND: sqlalchemy
    CACHE_REDIS_HOST: docker-cache
    CACHE_REDIS_PORT: 6379
    CACHE_LRU_REDIS_HOST: docker-cache
    CACHE_LRU_REDIS_PORT: 6379
docker-storage:
  image: busybox
  volumes:
    - /var/lib/docker/registry
  command:
    - 'true'
docker-cache:
  image: redis
