docker-registry:
  image: registry:2.4.1
  ports:
    - "5000:5000"
  labels:
    io.rancher.sidekicks: docker-storage
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:host_label_soft: docker=registry
  links:
    - docker-storage
  volumes_from:
    - docker-storage
  environment:
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
docker-storage:
  image: busybox
  labels:
    io.rancher.container.start_once: true
    io.rancher.container.pull_image: always
  volumes:
    - /var/lib/registry
