did-jenkins:
  image: "rancher/jenkins-swarm:v0.2.0"
  user: "root"
  labels:
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label_soft: ci=worker
  external_links:
    - "${jenkins_service}:jenkins-primary"
  environment:
    JENKINS_PASS: "${jenkins_pass}"
    JENKINS_USER: "${jenkins_user}"
    SWARM_EXECUTORS: "${swarm_executors}"
  volumes:
    - '/home/jenkins/workspace:/home/jenkins/workspace'
    - '/tmp:/tmp'
